[project]
name = 'flash-loan-provider'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.flash-loan]
path = 'contracts/flash-loan.clar'
clarity_version = 4
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
